### ISSUE TITLE
Unable to install on Python 3.6

### ISSUE THREAD

**Issue by mweinelt** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#59]
I'm on

```
Python 3.6.12 (default, Aug 15 2020, 06:59:32) 
```

Trying to install pyworld fails, because an incompatible numpy version gets picked:

```
$ python3 -m pip install pyworld
Collecting pyworld
  Using cached https://files.pythonhosted.org/packages/af/88/003eef396c966cf00088900167831946b80b8e7650843905cb9590c2d9ca/pyworld-0.2.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-prn30nce/numpy-1.20.0rc1/setup.py", line 30, in <module>
        import numpy
    RuntimeError: Python version >= 3.7 required.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e8oiu7lq/pyworld/setup.py", line 66, in <module>
        classifiers=[],
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/nix/store/l6zbxidx7l94r0i7k17ranxsw5id9141-python3-3.6.12/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/nix/store/l6zbxidx7l94r0i7k17ranxsw5id9141-python3-3.6.12/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-prn30nce/numpy-1.20.0rc1/setup.py", line 30, in <module>
        import numpy
    RuntimeError: Python version >= 3.7 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e8oiu7lq/pyworld/
```

Even pinning numpy to a working version does not resolve this.

```
$ python3 -m pip install pyworld numpy==1.19.4
Collecting pyworld
  Using cached https://files.pythonhosted.org/packages/af/88/003eef396c966cf00088900167831946b80b8e7650843905cb9590c2d9ca/pyworld-0.2.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ud6y04o8/numpy-1.20.0rc1/setup.py", line 30, in <module>
        import numpy
    RuntimeError: Python version >= 3.7 required.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_eke8onk/pyworld/setup.py", line 66, in <module>
        classifiers=[],
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/nix/store/l6zbxidx7l94r0i7k17ranxsw5id9141-python3-3.6.12/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/nix/store/l6zbxidx7l94r0i7k17ranxsw5id9141-python3-3.6.12/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/hexa/tmp/pyworld/env/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ud6y04o8/numpy-1.20.0rc1/setup.py", line 30, in <module>
        import numpy
    RuntimeError: Python version >= 3.7 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-_eke8onk/pyworld/
```

Based on current information I would recommend away from the legacy easy_install codepath and convert this project to use `pyproject.toml`, see https://github.com/pypa/pip/issues/9239#issuecomment-740030265.

Reported this issue over at https://github.com/pypa/pip/issues/9239

**Comment by JeremyCCHsu** [comment]
I couldn't reproduce this issue. I tried the following 2 configs, and `pyworld` worked fine on both:
1. Python 3.6.12 + Numpy 1.19.5  
2. Python 3.7.9  + Numpy 1.20.0rc1  

Please let me know what I can do to either reproduce the issue or to solve it. Feel free to open a PR, too.

P.S. I'm using Windows System Linux (Ubuntu 20.04).
